In [1]:
from datetime import datetime
from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator, BranchPythonOperator

import os
import pandas as pd
import FinanceDataReader as fdr
from datetime import datetime
from dateutil.relativedelta import relativedelta

import exchange_calendars as ecals

from dags.model import rasterize, inference

In [5]:
def predict(date):
    ks_date = datetime.strptime(date,'%Y-%m-%d')
    ks_date = ks_date + relativedelta(days=1)
    ks_date = ks_date.strftime("%Y-%m-%d")

    # 주식 코드 db 테이블에서 반복문으로 각 코드 가져오기
    file_name = f'./dags/database/symbol_data/korea_stock_symbols_2024-03-08.csv'
    stock_table = pd.read_csv(file_name)

    column = ['Date', 'Name', 'Code', 'Close_Price', \
                'Day_1', 'Day_2', 'Day_3', 'Day_4', 'Day_5', 'Day_6', 'Day_7']
    predict_df = pd.DataFrame(columns=column)


    for _, stock in stock_table.iterrows():
        
        code = stock['value'].split(':')[1]
        name = stock['label']

        close_price = fdr.DataReader(code, ks_date, ks_date).iloc[0]['Close']
        try:
            stock_image = rasterize(code, ks_date)
        except:
            print(code, ks_date)
            close_price = fdr.DataReader(code, ks_date, ks_date).iloc[0]['Close']
            
        preds = inference(stock_image)
        preds_result = []
        for idx, pct in preds:
            preds_result.append(str(idx)+'/'+str(round(pct,2)))
        
        result = [ks_date, name, code, close_price]
        result.extend(preds_result)

        predict_df = pd.concat([predict_df, pd.DataFrame([result],columns=column)])

    save_dir = './dags/database/predict_table'
    predict_df.to_csv(os.path.join(save_dir, f"predict_{ks_date}.csv"))

In [6]:
predict("2024-03-12")

/tmp/ipykernel_418572/1191070724.py:35 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

278470 2024-03-13
452430 2024-03-13
443670 2024-03-13
199430 2024-03-13
418620 2024-03-13
360350 2024-03-13
068100 2024-03-13
473050 2024-03-13
469900 2024-03-13
468760 2024-03-13
472230 2024-03-13
473370 2024-03-13

In [ ]:
278470 2024-03-13
452430 2024-03-13
443670 2024-03-13
199430 2024-03-13
418620 2024-03-13
360350 2024-03-13
068100 2024-03-13
473050 2024-03-13
469900 2024-03-13
468760 2024-03-13
472230 2024-03-13
473370 2024-03-13

In [7]:
folder_name = 'symbol_data'
file_name = 'korea_stock_symbols.csv'
file_path = os.path.join(folder_name, file_name)

# if not os.path.exists(folder_name):
#     os.makedirs(folder_name)

In [5]:
import pandas as pd
kospi_list = fdr.StockListing('KOSPI')
kosdaq_list = fdr.StockListing('KOSDAQ')
korea_stock_list = pd.concat([kospi_list, kosdaq_list])
korea_stock_symbol = korea_stock_list[['Code', 'Name']]

# columns = ['Code']
# korea_stock_symbol['Code'] = 'KRX:' + korea_stock_symbol['Code']

In [1]:
from tqdm import tqdm
import FinanceDataReader as fdr

In [6]:
code_list, name_list = [], []

In [17]:
df = fdr.DataReader(code,"2024-03-08").index
df

DatetimeIndex(['2024-03-08', '2024-03-11', '2024-03-12', '2024-03-13'], dtype='datetime64[ns]', name='Date', freq=None)

In [12]:
kospi_list = fdr.StockListing('KOSPI')
kosdaq_list = fdr.StockListing('KOSDAQ')
korea_stock_list = pd.concat([kospi_list, kosdaq_list])
korea_stock_symbol = korea_stock_list[['Code', 'Name']]

code_list, name_list = [], []
for _, stock in korea_stock_symbol.iterrows():
    code = stock['Code']
    name = stock['Name']
    if len(fdr.DataReader(code,"2024-03-08")) < 40:
        continue
    code_list.append(code)
    name_list.append(name)

korea_stock_df = pd.DataFrame({'Code': code_list, 'Name' : name_list})
korea_stock_df['Code'] = 'KRX:' + korea_stock_df['Code']

KeyboardInterrupt:

In [10]:
korea_stock_df

        Code        Name
0     005930        삼성전자
1     000660      SK하이닉스
2     373220    LG에너지솔루션
3     207940    삼성바이오로직스
4     005380         현대차
...      ...         ...
2642  161570  THE MIDONG
2643  413600     키움제6호스팩
2644  438580   엔에이치스팩25호
2645  032685       소프트센우
2646  021045      대호특수강우

[2647 rows x 2 columns]

In [11]:
korea_stock_df['Code'] = 'KRX:' + korea_stock_df['Code']
korea_stock_df

            Code        Name
0     KRX:005930        삼성전자
1     KRX:000660      SK하이닉스
2     KRX:373220    LG에너지솔루션
3     KRX:207940    삼성바이오로직스
4     KRX:005380         현대차
...          ...         ...
2642  KRX:161570  THE MIDONG
2643  KRX:413600     키움제6호스팩
2644  KRX:438580   엔에이치스팩25호
2645  KRX:032685       소프트센우
2646  KRX:021045      대호특수강우

[2647 rows x 2 columns]

In [9]:
fdr.DataReader('472230')

            Open  High   Low  Close    Volume    Change
Date
2024-03-04  4000  5700  2100   2100  89618041       NaN
2024-03-05  2105  2110  2065   2080   1844735 -0.009524
2024-03-06  2075  2080  2065   2075    332416 -0.002404
2024-03-07  2070  2090  2070   2080    255261  0.002410
2024-03-08  2095  2105  2085   2090    110000  0.004808
2024-03-11  2090  2100  2085   2090    146048  0.000000
2024-03-12  2085  2100  2085   2095     67992  0.002392
2024-03-13  2095  2095  2085   2095     64649  0.000000

In [35]:
import datetime
from dateutil.relativedelta import relativedelta

today = datetime.datetime.now()
bef = today - relativedelta(months=3)
bef_str = bef.strftime("%Y-%m-%d")
today_str = today.strftime("%Y-%m-%d")

In [36]:
print(bef_str, today_str)

2023-12-13 2024-03-13

In [40]:
stocks = fdr.StockListing('KOSPI')[['Code','Name']]
for code in stocks['Code']:
    df = fdr.DataReader(code,bef_str, today_str)
    break
df

             Open   High    Low  Close    Volume    Change
Date
2023-12-13  73300  73500  72800  72800  13116766 -0.009524
2023-12-14  74100  74300  72500  73100  27567593  0.004121
2023-12-15  73800  74000  73200  73300  15419815  0.002736
2023-12-18  73300  73400  72800  72900   9690551 -0.005457
2023-12-19  73000  73400  72800  73400   8907632  0.006859
2023-12-20  74200  74900  73800  74800  16870156  0.019074
2023-12-21  74600  75000  74300  75000  13478766  0.002674
2023-12-22  75800  76300  75400  75900  14515608  0.012000
2023-12-26  76100  76700  75700  76600  13164909  0.009223
2023-12-27  76700  78000  76500  78000  20651042  0.018277
2023-12-28  77700  78500  77500  78500  17797536  0.006410
2024-01-02  78200  79800  78200  79600  17142847  0.014013
2024-01-03  78500  78800  77000  77000  21753644 -0.032663
2024-01-04  76100  77300  76100  76600  15324439 -0.005195
2024-01-05  76700  77100  76400  76600  11304316  0.000000
2024-01-08  77000  77500  76400  76500  11088724 -0.001305
2024-01-09  77400  77700  74300  74700  26019249 -0.023529
2024-01-10  75000  75200  73200  73600  20259529 -0.014726
2024-01-11  72900  73600  72700  73200  57691266 -0.005435
2024-01-12  73000  74100  72800  73100  13038939 -0.001366
2024-01-15  73200  74000  73200  73900  13212339  0.010944
2024-01-16  73500  73700  72500  72600  14760415 -0.017591
2024-01-17  73100  73300  71000  71000  22683660 -0.022039
2024-01-18  71600  72000  70700  71700  17853397  0.009859
2024-01-19  73500  74700  73000  74700  23363427  0.041841
2024-01-22  75900  76000  75000  75100  19673375  0.005355
2024-01-23  75700  75800  74300  75200  14786224  0.001332
2024-01-24  75200  75200  73500  74000  12860661 -0.015957
2024-01-25  74200  74800  73700  74100  11737747  0.001351
2024-01-26  73700  74500  73300  73400  11160062 -0.009447
2024-01-29  73800  75200  73500  74400  13976521  0.013624
2024-01-30  75000  75300  73700  74300  12244418 -0.001344
2024-01-31  73400  74000  72500  72700  15703560 -0.021534
2024-02-01  73000  74200  72900  73600  19881033  0.012380
2024-02-02  74000  75200  73700  75200  14955881  0.021739
2024-02-05  74200  74800  73500  74300  19026021 -0.011968
2024-02-06  74300  74700  73300  74400  14559254  0.001346
2024-02-07  74600  75500  74300  75000  16566445  0.008065
2024-02-08  75000  75200  73600  74100  20810708 -0.012000
2024-02-13  74800  75200  74400  75200  21966745  0.014845
2024-02-14  73700  74300  73700  74000  12434945 -0.015957
2024-02-15  74200  74400  73000  73000  14120600 -0.013514
2024-02-16  73300  73400  72500  72800  13444781 -0.002740
2024-02-19  72800  73900  72800  73800  12726404  0.013736
2024-02-20  73700  73700  72800  73300  14681477 -0.006775
2024-02-21  73400  73700  72900  73000  11503495 -0.004093
2024-02-22  73800  73900  72700  73100  15208934  0.001370
2024-02-23  73600  74200  72900  72900  16225166 -0.002736
2024-02-26  72300  73200  72200  72800  14669352 -0.001372
2024-02-27  73100  73400  72700  72900  13201981  0.001374
2024-02-28  72900  73900  72800  73200  11795859  0.004115
2024-02-29  72600  73400  72000  73400  21176403  0.002732
2024-03-04  74300  75000  74000  74900  23210474  0.020436
2024-03-05  74600  74800  73700  73700  19505125 -0.016021
2024-03-06  73200  73500  72700  72900  21547905 -0.010855
2024-03-07  73100  73300  72200  72200  14516963 -0.009602
2024-03-08  72800  73400  72600  73300  19271349  0.015235
2024-03-11  72900  73100  72300  72400   9740504 -0.012278
2024-03-12  72600  73500  72100  73300  12948467  0.012431

In [8]:
kospi_list = fdr.StockListing('KOSPI')
kosdaq_list = fdr.StockListing('KOSDAQ')

korea_stock_list = pd.concat([kospi_list, kosdaq_list])

korea_stock_symbol = korea_stock_list[['Code', 'Name']]

korea_stock_symbol['Code'] = 'KRX:' + korea_stock_symbol['Code']

print(korea_stock_symbol.head())

         Code      Name
0  KRX:005930      삼성전자
1  KRX:000660    SK하이닉스
2  KRX:373220  LG에너지솔루션
3  KRX:207940  삼성바이오로직스
4  KRX:005935     삼성전자우

/tmp/ipykernel_123780/516760139.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  korea_stock_symbol['Code'] = 'KRX:' + korea_stock_symbol['Code']

In [27]:
korea_stock_symbol.rename(columns={'Name': 'label', 'Code': 'value'}, inplace=True)
korea_stock_symbol.to_csv(file_path, index=False, encoding='utf-8-sig')

print(f'CSV 파일이 {file_path}에 저장되었습니다.')

CSV 파일이 symbol_data/korea_stock_symbols.csv에 저장되었습니다.

/var/folders/b3/x6l_dngd7mxg34spbn8446pm0000gn/T/ipykernel_5337/1372236534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  korea_stock_symbol.rename(columns={'Name': 'label', 'Code': 'value'}, inplace=True)